version: "3.9"

services:
  asterisk:
    build: ./asterisk
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "8088:8088/tcp"
      - "5038:5038/tcp"
      - "10000-11000:10000-11000/udp"
    depends_on:
      - postgres
    networks:
      mynetwork:
        ipv4_address: 172.20.0.2

  postgres:
    build:
      context: ./postgres
    ports:
      - "5432:5432"
    networks:
      mynetwork:
        ipv4_address: 172.20.0.3

  nodejs:
    build: ./nodejs
    ports:
      - "3000:3000"
    depends_on:
      - asterisk
      - postgres
    networks:
      mynetwork:
        ipv4_address: 172.20.0.4

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - nodejs
    networks:
      mynetwork:
        ipv4_address: 172.20.0.5

networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
